Mobile menu
ilyassatlassi/portfolio pull request #14
Opened 2022-11-22 17:21 UTC by ilyassatlassi

Create a dynamic hamburger Menu by using javascript

2022-11-22 21:37 UTC, PinkMoon25 requested changes
Hi @ilyassatlassi @Patfarmurs ,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

### Highlights
Correct github flow :heavy_check_mark:
Added Readme :heavy_check_mark:
Implemented Js functionality :heavy_check_mark:

## Required Changes :recycle:
Check the comments under the review.

 I see that you have added eslint file but as you can see the eslint checks are not running, :point_down:

![image](https://user-images.githubusercontent.com/97521557/203427986-3c66d985-5aa6-4850-99c3-535c20af733b.png)

This might be because you hav not updated the .github/workflows linters.yml file please update the linters.yml file and make sure the eslint check is also running you can get the updated liners.yml file from [here](https://github.com/microverseinc/linters-config/blob/master/javascript/.github/workflows/linters.yml)

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!clapclapclap

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-11-22 21:37 UTC, PinkMoon25 commented on style.css
> +  }
- [ ] I think it will be better if we can improve the look of our mobile menu the current design blocks the menu links a little see :point_down: 
![image](https://user-images.githubusercontent.com/97521557/203424319-9e12c789-084b-476f-a0ed-19c92e59bff8.png)

And if we remove the `mix-blend-mode: multiply;` and reduce the `backdrop-filter: blur(10px);` and decrease the opacity of background color it will be like this :point_down: 
![image](https://user-images.githubusercontent.com/97521557/203424948-eba28926-426d-4ddd-9a22-2914ab28877a.png)

2022-11-22 21:37 UTC, PinkMoon25 commented on script/main.js
> +  cancel.classList.toggle('active');
[OPTIONAL] I see we are repeating the same block of code multiple times, by following the DRY principle we can group this in a function like 
```
const activeToggle = () => {
  menu.classList.toggle('active');
  links.classList.toggle('active');
  cancel.classList.toggle('active');
};
```
and then we can call activeToggle() each time where we need it instead of repeating the code, just a suggestin :+1:

2022-11-24 08:28 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle: :1st_place_medal: :100:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

## Hey @ilyassatlassi, @Patfarmurs :wave:

Great work on implementing the requested changes. Your project is complete. :blush:
There is nothing else to say about your project. :+1:


## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Github flow
✔️ Following requirements

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-26 14:04 UTC, merged